# syntax=docker/dockerfile:1
FROM composer:2.6.6 as deps
WORKDIR /app
RUN --mount=type=bind,source=composer.json,target=composer.json \
    --mount=type=bind,source=composer.lock,target=composer.lock \
    --mount=type=cache,target=/tmp/cache \
    composer install --no-interaction --ignore-platform-reqs --no-autoloader

FROM php:7.4-fpm-alpine3.16 as final

RUN apk update && apk add curl nano supervisor autoconf gcc make musl-dev lz4-dev zstd-dev
RUN echo "* * * * * php /app/artisan schedule:run >> /dev/null 2>&1" >> /etc/crontabs/www-data

RUN docker-php-ext-install pdo pdo_mysql pcntl
RUN pecl install igbinary msgpack && docker-php-ext-enable igbinary msgpack
RUN printf "yes\nyes\nyes\nyes\nyes\nyes\n" | pecl install redis && docker-php-ext-enable redis
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

COPY .docker/config/local/supervisor/supervisord.conf /etc/supervisord.conf
COPY .docker/config/local/supervisor/supervisor.d/ /etc/supervisor.d/

WORKDIR /app
COPY --from=deps /app/vendor/ /app/vendor
COPY --from=deps /usr/bin/composer /usr/bin/composer
COPY . .
RUN composer dump-autoload

RUN addgroup -g 1000 appgroup
RUN adduser -D -u 1000 appuser -G appgroup

CMD supervisord -n -c /etc/supervisord.conf
