# syntax=docker/dockerfile:1
FROM composer:2.6.6 as deps
WORKDIR /app
RUN --mount=type=bind,source=composer.json,target=composer.json \
    --mount=type=bind,source=composer.lock,target=composer.lock \
    --mount=type=cache,target=/tmp/cache \
    composer install --no-interaction --no-dev --ignore-platform-reqs --no-autoloader

FROM php:7.4-fpm-alpine3.16 as final

RUN apk update && apk add curl nano supervisor autoconf gcc make musl-dev lz4-dev zstd-dev
RUN echo "* * * * * php /app/artisan schedule:run >> /dev/null 2>&1" >> /etc/crontabs/www-data

RUN docker-php-ext-install pdo pdo_mysql pcntl
RUN pecl install igbinary msgpack && docker-php-ext-enable igbinary msgpack
RUN printf "yes\nyes\nyes\nyes\nyes\nyes\n" | pecl install redis && docker-php-ext-enable redis
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

COPY --chown=www-data:www-data .docker/config/production/supervisor/supervisord.conf /etc/supervisord.conf
COPY --chown=www-data:www-data .docker/config/production/supervisor/supervisor.d/ /etc/supervisor.d/


WORKDIR /var/www/html
COPY --from=deps /app/vendor/ /var/www/html/vendor
COPY --from=deps /usr/bin/composer /usr/bin/composer
COPY --chown=www-data:www-data . .
RUN mv .env.production .env
RUN composer dump-autoload -o --no-dev

USER www-data
WORKDIR /cetc

WORKDIR /var/www/html

CMD supervisord -n -c /etc/supervisord.conf
